TwitterClone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("twitter_app.urls")),
    path("",include('django.contrib.auth.urls'))
]

twitter_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "twitter_app"

urlpatterns = [
    path('',views.index,name="index"), #123123123123/twitter_app
    path('addtweet/',views.addtweet,name="addtweet"), #123123123123/twitter_app/addtweet
    path('addtweetbyform',views.addtweetbyform,name="addtweetbyform")
]

twitter_app/models.py
from django.db import models

# Create your models here.

class Tweet(models.Model):
    nickname = models.CharField(max_length=50)
    message = models.CharField(max_length=250)

    def __str__(self):
        return f"Nickname: {self.nickname} Message: {self.message}"

twitter_app/forms.py
from django import forms
from django.forms import ModelForm
from twitter_app.models import Tweet

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname",max_length=50) 
    message_input = forms.CharField(label="Message",max_length=150,widget=forms.Textarea(attrs={"class":"tweetarea"}))

twitter_app/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse
from twitter_app.forms import AddTweetForm
# Create your views here.

def index(request):
    all_tweets = models.Tweet.objects.all()
    tweets_dict = {"tweets" : all_tweets} 
    return render(request,'twitter_app/index.html', context=tweets_dict)

def addtweet(request):
    if request.POST:
        nickname = request.POST["nickname"]
        message = request.POST["message"]
        models.Tweet.objects.create(nickname=nickname, message=message)
        return redirect(reverse('twitter_app:index'))
    else:
        return render(request,'twitter_app/addtweet.html')
    
def addtweetbyform(request):
    if request.POST:
        form = AddTweetForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.Tweet.objects.create(nickname = nickname, message=message)
            return redirect(reverse('twitter_app:index'))
        else:
            print("Error")
            return render(request,'twitter_app/addtweetbyform.html',context={"form":form})
    else:  
        form = AddTweetForm()
        return render(request,'twitter_app/addtweetbyform.html',context={"form":form})

templates/base.html
{% load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Twitter Clone</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'twitter_app/customform.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Eighth navbar example">
      <div class="container p-3">
        <a class="navbar-brand" aria-current="page" href="{% url 'twitter_app:index' %}">Home</a>
        <ul>
          <li>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
          </li>
          <li>
            <button class="btn btn-primary"><a class="nav-link" href="{% url 'twitter_app:addtweet' %}">Add Tweet</a></button>
          </li>
          <li>
            <button class="btn btn-primary"><a class="nav-link" href="{% url 'login' %}">Login</a></button>
          </li>
        </ul>
        
        
        <!--<button class="btn btn-primary"><a class="nav-link" href="{% url 'twitter_app:addtweetbyform' %}">Add Tweet By Form</a></button> -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-3">
          
        </div> <div class="col-6">
          {%block content%}


          {%endblock%}
        </div> 
        <div class="col-3">

        </div>
      </div>
  
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

twitter_app/templates/twitter_app/addtweet.html
{% extends "base.html" %}

{%block content%}
<h1 class="page-title">Add tweet page</h1>
<br>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nickname" class="form-label">Nickname</label>
            <input type="text" class="form-control" id="nickname" name="nickname">
        </div>
        <div class="mb-3">
            <label for="message" class="form-label">Tweet</label>
            <input type="text" class="form-control" id="message" name="message">
        </div>
        <button type="submit" class="btn btn-primary">Add Tweet</button>
    </form>

{%endblock%}

twitter_app/templates/twitter_app/addtweetbyform.html
{% extends "base.html" %}
{% load static %}

{%block content%}
<h1 style="text-align: center;">Add tweet by Form</h1>
<br>

<div class="tweetform">
    <form action="" method="POST">
        {% csrf_token %}

        {%for field in form%}
        <div class="container p-3">
            {{field.label_tag}}
            {{field}}
        </div>
        {%endfor%}
        <button type="submit" class="btn btn-primary">Add Tweet</button>
    </form>
</div>

{%endblock%}

twitter_app/templates/twitter_app/index.html
{% extends "base.html" %}
{% load static%}

{%block content%}

    <h1 class="home-title">Home Page</h1>
    {%for tweet in tweets%}
    <!--
    <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">{{tweet.nickname}}</div>
        <div class="card-body text-bg-light">
          <p class="card-text">{{tweet.message}}</h3></p>
        </div>
    </div>
    -->
    <div class="card w-100 mb-3">
        <div class="card-body">
          <h5 class="card-title">{{tweet.nickname}}</h5>
          <hr>
          <p class="card-text">{{tweet.message}}</p>
        </div>
    </div>
    {%endfor%}



{%endblock%}